### ISSUE TITLE
DUDE USE VECTORS GOD DAMN YOU

### ISSUE THREAD

**Issue by Rex4499** [Lebert-130/Mjolnir#1]
YOU EVEN HAVE VECTOR.H HERE BRO WHY

**Comment by Lebert-130** [comment]
Fixed at https://github.com/Lebert-130/Mjolnir/commit/1b815d1d8fdecc5ac20812483eb82c7072090220

**Comment by Lebert-130** [comment]
Fixed at https://github.com/Lebert-130/Mjolnir/commit/1b815d1d8fdecc5ac20812483eb82c7072090220
